"""all table initiation

Revision ID: b7b7e529d607
Revises: dafd3e8129bf
Create Date: 2022-03-23 12:14:47.453460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7b7e529d607'
down_revision = 'dafd3e8129bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
