"""all table initiation

Revision ID: c9c70b824644
Revises: b7b7e529d607
Create Date: 2022-03-23 12:14:56.604123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c70b824644'
down_revision = 'b7b7e529d607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
