"""all table initiation

Revision ID: dafd3e8129bf
Revises: 
Create Date: 2022-03-23 12:09:52.984357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dafd3e8129bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('pgroup', sa.String(), nullable=True),
    sa.Column('group', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('total_students', sa.Integer(), nullable=True),
    sa.Column('buffer_size', sa.Integer(), nullable=True),
    sa.Column('is_physical', sa.String(), nullable=True),
    sa.Column('student', sa.String(), nullable=True),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
